using GamaGarage.mesagekutu;
using Microsoft.Data.SqlClient;
using System;
using System.Data;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace GamaGarage.Sayfalar
{
    public partial class Muhasebe : UserControl
    {
        DataTable dtMuhasebeGenel = new DataTable();

        public Muhasebe()
        {
            InitializeComponent();
            MuhasebeListele();
        }

        private void MuhasebeListele()
        {
            try
            {
                using (SqlConnection baglanti = new SqlConnection(App.BaglantiCumlesi))
                {
                    string sql = "SELECT IslemID, Tarih, Tutar, IslemTipi, Aciklama FROM View_KasaGenelRapor ORDER BY Tarih DESC";
                    SqlDataAdapter da = new SqlDataAdapter(sql, baglanti);
                    dtMuhasebeGenel = new DataTable();
                    da.Fill(dtMuhasebeGenel);

                    GiderFiltrele();
                    GelirFiltrele();
                }
            }
            catch (Exception ex)
            {
                GamaMesaj.Tamam("Veri yükleme hatası: " + ex.Message, "SİSTEM HATASI");
            }
        }

       
        private void GiderFiltrele()
        {
            if (dtMuhasebeGenel == null || dtMuhasebeGenel.Rows.Count == 0) return;

            DataView dvGider = new DataView(dtMuhasebeGenel);
            string filtre = "IslemTipi = 'GİDER'";

            if (!string.IsNullOrWhiteSpace(txtGiderAra.Text))
                filtre += $" AND Aciklama LIKE '%{txtGiderAra.Text}%'";

            if (dpGiderBaslangic.SelectedDate != null)
                filtre += $" AND Tarih >= '{dpGiderBaslangic.SelectedDate.Value:yyyy-MM-dd}'";
            if (dpGiderBitis.SelectedDate != null)
                filtre += $" AND Tarih <= '{dpGiderBitis.SelectedDate.Value:yyyy-MM-dd}'";

            dvGider.RowFilter = filtre;
            dgGider.ItemsSource = dvGider;

            decimal toplam = 0;
            foreach (DataRowView satir in dvGider) toplam += Convert.ToDecimal(satir["Tutar"]);
            lblToplamGider.Text = "₺ " + toplam.ToString("N2");
        }

    
        private void GelirFiltrele()
        {
            if (dtMuhasebeGenel == null || dtMuhasebeGenel.Rows.Count == 0) return;

            DataView dvGelir = new DataView(dtMuhasebeGenel);
            string filtre = "IslemTipi = 'GELİR'";

            if (!string.IsNullOrWhiteSpace(txtGelirAra.Text))
                filtre += $" AND Aciklama LIKE '%{txtGelirAra.Text}%'";

            if (dpGelirBaslangic.SelectedDate != null)
                filtre += $" AND Tarih >= '{dpGelirBaslangic.SelectedDate.Value:yyyy-MM-dd}'";
            if (dpGelirBitis.SelectedDate != null)
                filtre += $" AND Tarih <= '{dpGelirBitis.SelectedDate.Value:yyyy-MM-dd}'";

            dvGelir.RowFilter = filtre;
            dgGelir.ItemsSource = dvGelir;

            decimal toplam = 0;
            foreach (DataRowView satir in dvGelir) toplam += Convert.ToDecimal(satir["Tutar"]);
            lblToplamGelir.Text = "₺ " + toplam.ToString("N2");
        }

      
        private void btnGiderFiltre_Click(object sender, RoutedEventArgs e) => GiderFiltrele();
        private void txtGiderAra_TextChanged(object sender, TextChangedEventArgs e) => GiderFiltrele();
        private void btnGelirFiltre_Click(object sender, RoutedEventArgs e) => GelirFiltrele();
        private void txtGelirAra_TextChanged(object sender, TextChangedEventArgs e) => GelirFiltrele();

        private void dgGider_AutoGeneratedColumns(object sender, EventArgs e) => GridFormatla(sender as DataGrid);
        private void dgGelir_AutoGeneratedColumns(object sender, EventArgs e) => GridFormatla(sender as DataGrid);

        private void GridFormatla(DataGrid? dg)
        {
            if (dg == null) return;

            foreach (var col in dg.Columns)
            {
                if (col.Header == null) continue;
                string header = col.Header.ToString()!;

              
                if (header == "IslemID" || header == "IslemTipi")
                {
                    col.Visibility = Visibility.Collapsed;
                    continue;
                }

               
                switch (header)
                {
                    case "Tarih":
                        col.Header = "İşlem Tarihi";
                        col.Width = new DataGridLength(120); 
                        break;
                    case "Tutar":
                        col.Header = "Tutar (₺)";
                        col.Width = new DataGridLength(110);
                        break;
                    case "Aciklama":
                        col.Header = "Açıklama / Not";
                        col.Width = new DataGridLength(1, DataGridLengthUnitType.Star); 
                        break;
                }

               
                if (col is DataGridTextColumn textCol && textCol.Binding is Binding binding)
                {
                    if (header == "Tarih")
                        binding.StringFormat = "dd.MM.yyyy";
                    else if (header == "Tutar")
                        binding.StringFormat = "N2";
                }
            }
        }

        private void dgGelir_SelectionChanged(object sender, SelectionChangedEventArgs e) { }
        private void dgGider_SelectionChanged(object sender, SelectionChangedEventArgs e) { }
    }
}