using System;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Windows;
using System.Windows.Controls;

namespace GamaGarage.Sayfalar
{
    public partial class MusteriDetay : UserControl
    {
        public MusteriDetay()
        {
            InitializeComponent();
            MusteriListesiniYukle();
        }


        private void MusteriListesiniYukle()
        {
            string arama = txtMdetayAra.Text;
            DateTime? baslangic = dpMDetayBaslangic.SelectedDate;
            DateTime? bitis = dpMDetayBitis.SelectedDate;

            try
            {
                using (SqlConnection bag = new SqlConnection(App.BaglantiCumlesi))
                {

                    string sorgu = @"
                        SELECT Plaka, MAX(Ad) as Ad, MAX(Soyad) as Soyad, MAX(SonTarih) as [Son İşlem Tarihi] FROM (
                            SELECT AracPlaka as Plaka, Ad, Soyad, GETDATE() as SonTarih FROM Musteriler
                            UNION ALL
                            SELECT Plaka, Ad, Soyad, BaslangicTarih as SonTarih FROM Randevular ) AS Birlesik   WHERE Plaka IS NOT NULL AND Plaka <> ''";


                    if (!string.IsNullOrEmpty(arama))
                        sorgu += " AND (Ad LIKE @p OR Soyad LIKE @p OR Plaka LIKE @p)";
                    if (baslangic.HasValue)
                        sorgu += " AND SonTarih >= @bas";
                    if (bitis.HasValue)
                        sorgu += " AND SonTarih <= @bit";

                    sorgu += " GROUP BY Plaka ORDER BY [Son İşlem Tarihi] DESC";

                    SqlDataAdapter da = new SqlDataAdapter(sorgu, bag);
                    da.SelectCommand.Parameters.AddWithValue("@p", "%" + arama + "%");
                    if (baslangic.HasValue) da.SelectCommand.Parameters.AddWithValue("@bas", baslangic.Value);
                    if (bitis.HasValue) da.SelectCommand.Parameters.AddWithValue("@bit", bitis.Value);

                    DataTable dt = new DataTable();
                    da.Fill(dt);
                    dgMusteriListe.ItemsSource = dt.DefaultView;
                }
            }
            catch (Exception ex) { MessageBox.Show("Müşteri listesi hatası: " + ex.Message); }
        }

        private void dgMDetay_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var col in dgMusteriListe.Columns)
            {
                string header = col.Header?.ToString() ?? "";

               
                switch (header)
                {
                    case "Plaka": col.Header = "Araç Plakası"; break;
                    case "Ad": col.Header = "Adı"; break;
                    case "Soyad": col.Header = "Soyadı"; break;
                    case "Son İşlem Tarihi": col.Header = "Son İşlem Tarihi"; break;
                }

               
                if (header == "Son İşlem Tarihi" && col is DataGridTextColumn dateCol)
                {
                    (dateCol.Binding as System.Windows.Data.Binding)!.StringFormat = "dd.MM.yyyy";
                }
            }
        }


        private void dgMDetay_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            DetaylariYukle();
        }

        private void DetaylariYukle()
        {
            if (dgMusteriListe.SelectedItem == null) return;

            DataRowView satir = (DataRowView)dgMusteriListe.SelectedItem;
            string plaka = satir["Plaka"].ToString()!;
            string arama2 = txtMDetayAra2.Text;
            DateTime? baslangic2 = dpMDetayBaslangic2.SelectedDate;
            DateTime? bitis2 = dpMGelirBitis2.SelectedDate;
            try
            {
                using (SqlConnection bag = new SqlConnection(App.BaglantiCumlesi))
                {

                    string idSorgu = "SELECT MusteriID FROM Musteriler WHERE AracPlaka = @p";
                    SqlCommand idCmd = new SqlCommand(idSorgu, bag);
                    idCmd.Parameters.AddWithValue("@p", plaka);
                    bag.Open();
                    object mIDObj = idCmd.ExecuteScalar();
                    int mID = mIDObj != null ? Convert.ToInt32(mIDObj) : -1;
                    bag.Close();

                    string detaySorgu = @"
                        SELECT * FROM ( SELECT  BaslangicTarih as [İşlem Tarihi],   IslemTipi as [İşlem Türü],   Aciklama as [Detay],   Tutar as [Borç/Tutar],   0.00 as [Ödenen]     FROM Randevular WHERE Plaka = @plaka     UNION ALL
                            
                    SELECT   IslemTarihi as [İşlem Tarihi],   'ÖDEME' as [İşlem Türü],      Aciklama as [Detay],         0.00 as [Borç/Tutar],     Odenen as [Ödenen]     FROM MusteriOdemeleri WHERE MusteriID = @mid  ) AS Sonuc WHERE 1=1";

                    if (!string.IsNullOrEmpty(arama2))
                        detaySorgu += " AND ([Detay] LIKE @p2 OR [İşlem Türü] LIKE @p2)";
                    if (baslangic2.HasValue)
                        detaySorgu += " AND [İşlem Tarihi] >= @bas2";
                    if (bitis2.HasValue)
                        detaySorgu += " AND [İşlem Tarihi] <= @bit2";

                    detaySorgu += " ORDER BY [İşlem Tarihi] DESC";

                    SqlCommand cmd = new SqlCommand(detaySorgu, bag);
                    cmd.Parameters.AddWithValue("@plaka", plaka);
                    cmd.Parameters.AddWithValue("@mid", mID);
                    cmd.Parameters.AddWithValue("@p2", "%" + arama2 + "%");
                    if (baslangic2.HasValue) cmd.Parameters.AddWithValue("@bas2", baslangic2.Value);
                    if (bitis2.HasValue) cmd.Parameters.AddWithValue("@bit2", bitis2.Value);

                    SqlDataAdapter da = new SqlDataAdapter(cmd);
                    DataTable dt = new DataTable();
                    da.Fill(dt);
                    dgMDetayListe.ItemsSource = dt.DefaultView;
                }
            }
            catch (Exception ex) { MessageBox.Show("Detay Hatası: " + ex.Message); }
        }


        private void dgMDetayListe_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var col in dgMDetayListe.Columns)
            {
                string header = col.Header?.ToString() ?? "";
                col.Width = new DataGridLength(1, DataGridLengthUnitType.Star);

        
                if (col is DataGridTextColumn textCol && textCol.Binding is System.Windows.Data.Binding binding)
                {
                    if (header == "İşlem Tarihi")
                    {
                        binding.StringFormat = "dd.MM.yyyy HH:mm";
                    }
                    else if (header == "Borç/Tutar" || header == "Ödenen")
                    {
                        binding.StringFormat = "N2"; 
                        Style sagStyle = new Style(typeof(DataGridCell));
                        sagStyle.Setters.Add(new Setter(TextBlock.TextAlignmentProperty, TextAlignment.Right));
                        textCol.CellStyle = sagStyle;
                    }
                }

               
                if (header == "Detay") col.Header = "Açıklama / Detay";
            }
        }


        private void txtMdetayAra_TextChanged(object sender, TextChangedEventArgs e) => MusteriListesiniYukle();
        private void btnDetayFiltre_Click(object sender, RoutedEventArgs e) => MusteriListesiniYukle();


        private void txtMDetayAra2_TextChanged(object sender, TextChangedEventArgs e) => DetaylariYukle();
        private void btnMDetayFiltre2_Click(object sender, RoutedEventArgs e) => DetaylariYukle();

        private void btnMKapat_Click(object sender, RoutedEventArgs e)
        {
            if (this.Parent is ContentControl parentKonteynir)
            {
                parentKonteynir.Content = new MusteriSayfasi();
            }
        }
    }
}